/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as IntellectualSystemRouteImport } from './routes/intellectual-system'
import { Route as ResearchSeriesRouteImport } from './routes/research-series'
import { Route as FoundationalWorksRouteImport } from './routes/foundational-works'
import { Route as ResearchRouteImport } from './routes/research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const IntellectualSystemRoute = IntellectualSystemRouteImport.update({
  id: '/intellectual-system',
  path: '/intellectual-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSeriesRoute = ResearchSeriesRouteImport.update({
  id: '/research-series',
  path: '/research-series',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationalWorksRoute = FoundationalWorksRouteImport.update({
  id: '/foundational-works',
  path: '/foundational-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/theory': typeof TheoryRoute
  '/units': typeof UnitsRoute
  '/intellectual-system': typeof IntellectualSystemRoute
  '/research-series': typeof ResearchSeriesRoute
  '/foundational-works': typeof FoundationalWorksRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/theory': typeof TheoryRoute
  '/units': typeof UnitsRoute
  '/intellectual-system': typeof IntellectualSystemRoute
  '/research-series': typeof ResearchSeriesRoute
  '/foundational-works': typeof FoundationalWorksRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/theory': typeof TheoryRoute
  '/units': typeof UnitsRoute
  '/intellectual-system': typeof IntellectualSystemRoute
  '/research-series': typeof ResearchSeriesRoute
  '/foundational-works': typeof FoundationalWorksRoute
  '/research': typeof ResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/knowledge'
    | '/partnerships'
    | '/programs'
    | '/theory'
    | '/units'
    | '/intellectual-system'
    | '/research-series'
    | '/foundational-works'
    | '/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/knowledge'
    | '/partnerships'
    | '/programs'
    | '/theory'
    | '/units'
    | '/intellectual-system'
    | '/research-series'
    | '/foundational-works'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/knowledge'
    | '/partnerships'
    | '/programs'
    | '/theory'
    | '/units'
    | '/intellectual-system'
    | '/research-series'
    | '/foundational-works'
    | '/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PartnershipsRoute: typeof PartnershipsRoute
  ProgramsRoute: typeof ProgramsRoute
  TheoryRoute: typeof TheoryRoute
  UnitsRoute: typeof UnitsRoute
  IntellectualSystemRoute: typeof IntellectualSystemRoute
  ResearchSeriesRoute: typeof ResearchSeriesRoute
  FoundationalWorksRoute: typeof FoundationalWorksRoute
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intellectual-system': {
      id: '/intellectual-system'
      path: '/intellectual-system'
      fullPath: '/intellectual-system'
      preLoaderRoute: typeof IntellectualSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-series': {
      id: '/research-series'
      path: '/research-series'
      fullPath: '/research-series'
      preLoaderRoute: typeof ResearchSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundational-works': {
      id: '/foundational-works'
      path: '/foundational-works'
      fullPath: '/foundational-works'
      preLoaderRoute: typeof FoundationalWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  KnowledgeRoute: KnowledgeRoute,
  PartnershipsRoute: PartnershipsRoute,
  ProgramsRoute: ProgramsRoute,
  TheoryRoute: TheoryRoute,
  UnitsRoute: UnitsRoute,
  IntellectualSystemRoute: IntellectualSystemRoute,
  ResearchSeriesRoute: ResearchSeriesRoute,
  FoundationalWorksRoute: FoundationalWorksRoute,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
